# Generated by Django 4.2 on 2024-04-08 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_extenduser_usuarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='profile',
            new_name='usuario',
        ),
    ]
