# Generated by Django 4.2 on 2024-04-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuarios_dni_usuarios_imagen_usuarios_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='dni',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='cuil',
            field=models.PositiveIntegerField(default=27373129, unique=True),
            preserve_default=False,
        ),
    ]
