# Generated by Django 4.2 on 2024-03-27 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0005_empleadoevento_evento_tipoevento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoevento',
            old_name='tipo',
            new_name='nombre',
        ),
    ]
