# Generated by Django 4.2 on 2024-03-20 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Barrio',
                'verbose_name_plural': 'Barrios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sedes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('calle', models.CharField(blank=True, max_length=250, null=True)),
                ('altura', models.IntegerField(blank=True, null=True)),
                ('piso', models.CharField(blank=True, max_length=100, null=True)),
                ('presidente', models.CharField(blank=True, max_length=250, null=True)),
                ('telefono', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('mapa', models.CharField(blank=True, max_length=350, null=True)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='sedes')),
                ('observaciones', models.CharField(blank=True, max_length=800, null=True)),
                ('barrios', models.ManyToManyField(blank=True, to='sedes.barrios')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('observaciones', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tramites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('turnos', models.BooleanField(default=False)),
                ('espontaneos', models.BooleanField(default=False)),
                ('observaciones', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fk_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedes.servicios')),
            ],
            options={
                'verbose_name': 'Tramite',
                'verbose_name_plural': 'Tramites',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SedesPlanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planos', models.FileField(upload_to='sedes/planos/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=12)),
                ('fk_sedes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedes.sedes')),
            ],
        ),
        migrations.CreateModel(
            name='SedesArchivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='sedes/archivos/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=12)),
                ('fk_sedes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedes.sedes')),
            ],
        ),
        migrations.AddField(
            model_name='sedes',
            name='tramites',
            field=models.ManyToManyField(blank=True, to='sedes.tramites'),
        ),
    ]
