# Generated by Django 4.2 on 2024-04-24 18:14

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sedes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketGOPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('ticket', models.CharField(max_length=100)),
                ('otra_sede', models.CharField(max_length=250)),
                ('subsede', models.CharField(max_length=250)),
                ('nombre', models.CharField(max_length=250)),
                ('apellido', models.CharField(max_length=250)),
                ('CUIT', models.CharField(max_length=250)),
                ('mail', models.CharField(max_length=250)),
                ('area', models.CharField(max_length=250)),
                ('organismo', models.CharField(max_length=250)),
                ('nombre_agenda', models.CharField(max_length=250)),
                ('fecha_publicacion', models.DateField()),
                ('fecha_primer_turno', models.DateField()),
                ('max_turnos', models.IntegerField()),
                ('dias_atencion', models.CharField(max_length=250)),
                ('banda_horaria', models.CharField(max_length=250)),
                ('duracion_tramite', models.CharField(max_length=250)),
                ('cant_turnos_simultaneo', models.IntegerField()),
                ('tiempo_precancelacion', models.IntegerField()),
                ('visibilidad_agenda', models.IntegerField()),
                ('cupos_citas_diarios', models.IntegerField()),
                ('popup', models.TextField(blank=True, null=True)),
                ('txt_mail_confirmacion', models.TextField(blank=True, null=True)),
                ('login_BA', models.BooleanField()),
                ('documentos_requeridos', models.CharField(max_length=250)),
                ('vecino_reagendar_cita', models.BooleanField()),
                ('url_tramite', models.URLField()),
                ('estado', models.CharField(max_length=250)),
                ('fk_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedes.sedes')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
