# Generated by Django 4.2 on 2024-04-30 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkt_GOPA', '0002_alter_ticketgopa_cuit_alter_ticketgopa_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketgopa',
            name='otra_sede',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Otra sede'),
        ),
        migrations.AlterField(
            model_name='ticketgopa',
            name='subsede',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Subsede'),
        ),
        migrations.AlterField(
            model_name='ticketgopa',
            name='ticket',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ticket'),
        ),
    ]
