# Generated by Django 4.2 on 2024-04-30 03:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkt_GOPA', '0005_diassemana_alter_ticketgopa_dias_atencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketgopa',
            name='CUIT',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='El CUIT debe contener exactamente 11 dígitos numéricos.', regex='^[0-9]{11}$')], verbose_name='CUIT'),
        ),
    ]
