# Generated by Django 4.2 on 2024-04-29 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0001_initial'),
        ('tkt_GOPA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketgopa',
            name='CUIT',
            field=models.CharField(max_length=250, verbose_name='CUIT'),
        ),
        migrations.AlterField(
            model_name='ticketgopa',
            name='apellido',
            field=models.CharField(max_length=250, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='ticketgopa',
            name='area',
            field=models.CharField(max_length=250, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='ticketgopa',
            name='banda_horaria',
            field=models.CharField(max_length=250, verbose_name='Banda horaria de atención'),
        ),
        migrations.AlterField(
            model_name='ticketgopa',
            name='cant_turnos_simultaneo',
            field=models.IntegerField(verbose_name='Cantidad de turnos en simultaneo'),
        ),
        migrations.AlterField(
            model_name='ticketgopa',
            name='cupos_citas_diarios',
            field=models.IntegerField(verbose_name='Cantidad de cupos de citas diarios'),
        ),
        migrations.AlterField(
            model_name='ticketgopa',
            name='dias_atencion',
            field=models.CharField(max_length=250, verbose_name='Dias de atención'),
        ),
        migrations.AlterField(
            model_name='ticketgopa',
            name='documentos_requeridos',
            field=models.CharField(max_length=250, verbose_name='Documentación requerida'),
        ),
        migrations.AlterField(
            model_name='ticketgopa',
            name='duracion_tramite',
            field=models.CharField(max_length=250, verbose_name='Duracion del tramite'),
        ),
        migrations.AlterField(
            model_name='ticketgopa',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=250),
        ),
        migrations.AlterField(
            model_name='ticketgopa',
            name='fecha_primer_turno',
            field=models.DateField(verbose_name='Fecha del primer turno'),
        ),
        migrations.AlterField(
            model_name='ticketgopa',
            name='fecha_publicacion',
            field=models.DateField(verbose_name='Fecha de publicacion'),
        ),
        migrations.AlterField(
            model_name='ticketgopa',
            name='fk_sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sedes.sedes', verbose_name='Sede'),
        ),
        migrations.AlterField(
            model_name='ticketgopa',
            name='login_BA',
            field=models.BooleanField(verbose_name='Requiere Login con MiBA?'),
        ),
        migrations.AlterField(
            model_name='ticketgopa',
            name='mail',
            field=models.CharField(max_length=250, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='ticketgopa',
            name='max_turnos',
            field=models.IntegerField(verbose_name='Maxima cantidad de turnos por ciudadano'),
        ),
        migrations.AlterField(
            model_name='ticketgopa',
            name='nombre',
            field=models.CharField(max_length=250, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='ticketgopa',
            name='nombre_agenda',
            field=models.CharField(max_length=250, verbose_name='Nombre de la agenda'),
        ),
        migrations.AlterField(
            model_name='ticketgopa',
            name='organismo',
            field=models.CharField(max_length=250, verbose_name='Organismo'),
        ),
        migrations.AlterField(
            model_name='ticketgopa',
            name='otra_sede',
            field=models.CharField(max_length=250, verbose_name='Otra sede'),
        ),
        migrations.AlterField(
            model_name='ticketgopa',
            name='popup',
            field=models.TextField(blank=True, null=True, verbose_name='Leyenda que figura antes de confirmar el turno'),
        ),
        migrations.AlterField(
            model_name='ticketgopa',
            name='subsede',
            field=models.CharField(max_length=250, verbose_name='Subsede'),
        ),
        migrations.AlterField(
            model_name='ticketgopa',
            name='ticket',
            field=models.CharField(max_length=100, verbose_name='Ticket'),
        ),
        migrations.AlterField(
            model_name='ticketgopa',
            name='tiempo_precancelacion',
            field=models.IntegerField(verbose_name='Tiempo de precancelación. (En minutos)'),
        ),
        migrations.AlterField(
            model_name='ticketgopa',
            name='txt_mail_confirmacion',
            field=models.TextField(blank=True, null=True, verbose_name='Texto en el mail de confirmación.'),
        ),
        migrations.AlterField(
            model_name='ticketgopa',
            name='vecino_reagendar_cita',
            field=models.BooleanField(verbose_name='El vecino puede reagendar cita?'),
        ),
        migrations.AlterField(
            model_name='ticketgopa',
            name='visibilidad_agenda',
            field=models.IntegerField(verbose_name='Visibilidad de agenda. (En dias hábiles)'),
        ),
    ]
