# Generated by Django 4.2 on 2024-04-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkt_GOPA', '0006_alter_ticketgopa_cuit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketgopa',
            name='dias_atencion',
        ),
        migrations.AddField(
            model_name='ticketgopa',
            name='dias_atencion',
            field=models.ManyToManyField(to='tkt_GOPA.diassemana', verbose_name='Días de atención'),
        ),
    ]
