# Generated by Django 4.2 on 2024-04-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkt_GOPA', '0009_alter_ticketgopa_banda_horaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketgopa',
            name='estado',
            field=models.CharField(blank=True, default='Pendiente', max_length=250, null=True),
        ),
    ]
