# Generated by Django 4.2 on 2024-06-24 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkt_GOPA', '0010_alter_ticketgopa_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketgopa',
            name='banda_horaria',
        ),
        migrations.RemoveField(
            model_name='ticketgopa',
            name='cant_turnos_simultaneo',
        ),
        migrations.RemoveField(
            model_name='ticketgopa',
            name='cupos_citas_diarios',
        ),
        migrations.RemoveField(
            model_name='ticketgopa',
            name='dias_atencion',
        ),
        migrations.RemoveField(
            model_name='ticketgopa',
            name='duracion_tramite',
        ),
        migrations.RemoveField(
            model_name='ticketgopa',
            name='tiempo_precancelacion',
        ),
    ]
